### ISSUE TITLE
How to parse C files through Java API?

### ISSUE THREAD

**Issue by SherloqueChang** [GumTreeDiff/tree-sitter-parser#2]
I've installed `tree-sitter-parser`, but how can I get C code edit actions by invoking Java API in a Java project? The original implementaion is using `cgum`, but my OS is windows and I couldn't compile it.
Here is my code:

        Run.initGenerators();

        Tree src = null; // retrieves and applies the default parser for the file
        try {
            src = TreeGenerators.getInstance().getTree(srcFile).getRoot();
            Tree dst = TreeGenerators.getInstance().getTree(dstFile).getRoot(); // retrieves and applies the default parser for the file
            Matcher defaultMatcher = Matchers.getInstance().getMatcher(); // retrieves the default matcher
            MappingStore mappings = defaultMatcher.match(src, dst); // computes the mappings between the trees
            EditScriptGenerator editScriptGenerator = new SimplifiedChawatheScriptGenerator(); // instantiates the simplified Chawathe script generator
            EditScript actions = editScriptGenerator.computeActions(mappings); // computes the edit script
            List<Action> actionsList = actions.asList();
            for(Action action: actionsList) {
                System.out.println(action);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }`

**Comment by jrfaller** [comment]
Hi!

You have to force the tree sitter backend like this:

~~~
Tree src = new CTreeSitterTreeGenerator().generateFrom().file(srcFile).getRoot();
Tree dst = new CTreeSitterTreeGenerator().generateFrom().file(dstFile).getRoot();
~~~

If everything is installed correctly and you have a very recent clone of GumTree, it should work :-)

Cheers!

**Comment by SherloqueChang** [comment]
Ahh...another question here: why should I have a clone of GumTree?

I'm using Maven dependency like:
`
<dependency>
      <groupId>com.github.gumtreediff</groupId>
      <artifactId>client</artifactId>
      <version>3.0.0</version>
</dependency>
`

In this case, can I just add dependency in my pom.xml file? If so, what should <version> be?

**Comment by jrfaller** [comment]
Sorry, but the tree sitter integration has not yet been released to Maven!

**Comment by SherloqueChang** [comment]
Ok, I understand now. Thanks a lot!
