### ISSUE TITLE
tests: Agree on (and add) a test framework.

### ISSUE THREAD

**Issue by duesee** [GumTreeDiff/tree-sitter-parser#7]
We probably want some tests here that assure that `tree-sitter-parser` does what we expect it to do.

Before writing tests, we need to agree on a test framework. `pytest` seems easy to use and less verbose than Python's `unittest`.

**Comment by jrfaller** [comment]
I completely agree! Below are some thoughts I made on the PR for Rust :

**Comment by jrfaller** [comment]
It's not trivial to have tests in this project. Ideally we could have the code snippets directly in the test files. I guess the goal of the tests would be to assert we have the expected tree shapes when applying the rewrite rules, but it's kind of a tough (and boring) oracle to write. Not sure how to do better though...

**Comment by duesee** [comment]
The thing I noted after I made the Rust PR was the following:

Both, ...

`test1.rs`
```rust
fn main() {
  let x = "A";
}
```

... and ...

`test2.rs`
```rust
fn main() {
  let x = "B";
}
```

... produced the same XML output when executed without the "flattened" attribute in the config ...

```xml
<?xml version="1.0" ?>
<tree type="source_file" pos="0" length="29">
	<tree type="function_item" pos="0" length="28">
		<tree type="fn" pos="0" length="2" label="fn"/>
		<tree type="identifier" pos="3" length="4" label="main"/>
		<tree type="parameters" pos="7" length="2">
			<tree type="(" pos="7" length="1" label="("/>
			<tree type=")" pos="8" length="1" label=")"/>
		</tree>
		<tree type="block" pos="10" length="18">
			<tree type="{" pos="10" length="1" label="{"/>
			<tree type="let_declaration" pos="14" length="12">
				<tree type="let" pos="14" length="3" label="let"/>
				<tree type="identifier" pos="18" length="1" label="x"/>
				<tree type="=" pos="20" length="1" label="="/>
				<tree type="string_literal" pos="22" length="3">
					<tree type="&quot;" pos="22" length="1" label="&quot;"/>
					<tree type="&quot;" pos="24" length="1" label="&quot;"/>
				</tree>
				<tree type=";" pos="25" length="1" label=";"/>
			</tree>
			<tree type="}" pos="27" length="1" label="}"/>
		</tree>
	</tree>
</tree>
```

The reason is that tree-sitter does not output a node that contains the value of the string literal but two children with `type="&quot;"`. Thus, when I toyed around with GumTree, it showed an empty diff.

After fixing this by flattening the `string_literal` node I started to wonder if there are more of this instances and how one could detect that. I have no good idea so far but thought that it can't hurt to collect things we don't want to happen.

**Comment by jrfaller** [comment]
Right, nicely spotted! I had this problem with Ocaml too (and made the same fix) I think it comes from how tree-sitter handle strings in these grammars. But normally it is not supposed to happen ;-). There should be a child of string_literal that has the value of the string... Maybe something I don't understand with tree-sitter.

But I guess that given that it might happen, your isomorphism test is useful, and this is one kind of assert we need. However I have no idea if we can have this problem on other productions.

A second useful assert is to ensure two trees have the same structure with possibly different labels. This is for expressions like `a + b` vs `a - b` usually I like it to have the `+` to `-` represented as un update, therefore these nodes needs an identical type.

**Comment by duesee** [comment]
> But I guess that given that it might happen, your isomorphism test is useful, and this is one kind of assert we need. However I have no idea if we can have this problem on other productions.

Something I thought about when you said "isomorphism": Maybe we could try a property-based test. We could say that we want ...

```python
code == xml_to_code(code_to_xml(code))
```
... for a bunch of (randomly generated) inputs. When information -- such as the literal value -- is dropped during `code_to_xml`, it won't be possible to recreate the original.

Not sure how difficult it would be to write a `xml_to_code` function nor even if we can (and want to) recreate the code exactly. But that could cover similar cases to the string_literal one and would be language agnostic?

> A second useful assert is to ensure two trees have the same structure with possibly different labels. This is for expressions like a + b vs a - b usually I like it to have the + to - represented as un update, therefore these nodes needs an identical type.

Would you add that as a "handwritten test", i.e., define the expected values for `+`, `-`, etc.?

**Comment by jrfaller** [comment]
Indeed a property-based roundtrip test could be interesting, unfortunately we do not have pretty printers in GumTree and it would be a lot of tough work to integrate pretty printing in a generic way. In most parsers I think that the AST used by GumTree after rework would raise ambiguities if we tried to pretty print them. At the core, when diffing we care about important syntactic elements therefore some of the elements required to have pretty printing working are lost. One solution would be to diff full fledged CSTs and configure the algorithm to ignore irrelevant elements, but this is not at all what's done at the moment. This is however an interesting direction. Unfortunately tree-sitter for instance do not provide off the shelve pretty printers :-( (https://github.com/tree-sitter/tree-sitter/issues/603).

The idea for the iso structure tests have been tried in the test harness from GumTree (https://github.com/GumTreeDiff/gumtree/blob/main/gen.treesitter/src/test/java/com/github/gumtreediff/gen/treesitter/TreeSitterJavaTreeGeneratorTest.java) when I was working on the rewrite rules for Java. You can look at it to see if it's easy to understand what the test ensures and how it can help create a good configuration.
